# Generated by Django 5.1.4 on 2024-12-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passanger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passanger',
            new_name='Passenger',
        ),
    ]
